INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-32')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-21')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-31')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITP-12')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITI-22')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITP-21')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-41')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITI-31')
INSERT [dbo].[Groups] ([Name]) VALUES (N'ITP32')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IP-11')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-21')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-22')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-11')
INSERT [dbo].[Groups] ([Name]) VALUES (N'IS-12')


INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (1, 1)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (1, 2)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (1, 3)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (1, 4)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (2, 1)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (2, 2)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (2, 3)
INSERT [dbo].[Sessions] ([GroupId], [SessionNumber]) VALUES (2, 4)


INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (1, N'OOP', N'Exam', CAST(N'2020-05-09' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (1, N'OAIP', N'Exam', CAST(N'2020-05-19' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (1, N'Math', N'Credit', CAST(N'2020-05-06' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (3, N'History', N'Exam', CAST(N'2020-05-15' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (3, N'SUBD', N'Credit', CAST(N'2020-05-23' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (3, N'TVIMS', N'Credit', CAST(N'2020-06-09' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (3, N'SMAZAR', N'Credit', CAST(N'2020-06-11' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (2, N'Physics', N'Exam', CAST(N'2020-06-15' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (2, N'OOP', N'Exam', CAST(N'2020-06-19' AS Date))
INSERT [dbo].[EducationalSubjects] ([SessionId], [SubjectName], [SubjectType], [Date]) VALUES (2, N'MCHA', N'Exam', CAST(N'2020-06-24' AS Date))


INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Shyshkavets Pavel Sergeevich', N'Male', CAST(N'2000-05-09' AS Date), 1)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Reita Match Sergeevna', N'Woman', CAST(N'2001-06-11' AS Date), 3)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Artem Lukavtsov Gennadevich', N'Male', CAST(N'2000-02-13' AS Date), 2)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Borisenko Ivan Sergeevich', N'Male', CAST(N'2002-08-19' AS Date), 3)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Chaykov Andey Vasllyevich', N'Male', CAST(N'2003-03-03' AS Date), 1)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Palatkin Daniil Aleksandrovich', N'Male', CAST(N'2000-09-21' AS Date), 4)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Pankova Anastasiya Evgenevna', N'Woman', CAST(N'2001-01-01' AS Date), 4)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Gruzdov Pavel Genadevich', N'Male', CAST(N'2002-03-26' AS Date), 5)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Galavneva Ekaterina Genadevna', N'Woman', CAST(N'2000-06-19' AS Date), 6)
INSERT [dbo].[Students] ([FullName], [Gender], [DateOfBirth], [GroupId]) VALUES (N'Saykov Anatoliy Sergeevich', N'Male', CAST(N'2001-09-13' AS Date), 6)


INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (7, 1, N'8')
INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (8, 3, N'9')
INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (7, 3, N'6')
INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (9, 4, N'7')
INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (10, 5, N'10')
INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (8, 1, N'4')
INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (9, 1, N'2')
INSERT [dbo].[StudentResults] ([StudentId], [EducationalSubjectSubjectId], [Mark]) VALUES (9, 6, N'5')